[package]
name = "ray_tracer"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "4.5.9", features = ["cargo"] }
image = "0.25.1"
indicatif = "0.17.8"
rand = "0.8.5"
